### ISSUE TITLE
1Hive DAO Kit

### ISSUE THREAD

**Issue by yeqbfgxjiq** [1Hive/grants#8]
1Hive is a decentralized autonomous organization working to grow the open source commons and improve open source sustainability.

@burrrata 
- I think it’s important that we don’t sell ourselves short here and not include the 1Hive model. [The Aragon ecosystem needs examples of DAOs that are functional, well documented, and reproducable](https://forum.aragon.org/t/aragon-evolution-meta-strategy/940/2). We’re building that. Not only is 1Hive functioning (mostly), well documented (getting there), and reproducable (DAO template is on the radar), but we’re solving a hard problem in the Computer Science space that has been intractable for decades: sustainable community governed open source development. I think that on it’s own deserves a Nest Grant just for the sheer awesomeness and awareness it will bring to Aragon as a tool that could change the way people build software on the internet.

@0xGabi 
- Agree. I think it would be cool to include with the proposal some allocations of HONEY to the Flocks teams and the AA. So they can curate issues they would like to solve, engage with 1Hive and at the same time incentivize contribution form the comunity

@lkngtn 
- I'm on the fence about giving out honey at this point for grants, given that the grant would have a specific scope of work already. I do think it could be interesting to ask for ANT (possibly vested) as a way to align incentives between the 1hive org and Aragon. 

@0xGabi 
- I do agree that 1hive and the documentation work we are doing is also really valuable to Aragon, I don't think alone it warrants a nest proposal, but perhaps creating a proposal based on documentation and onboarding work we are doing would make sense. 

@0xGabi 
- Understood, agree that narrow the initial scope is important
- +1 on ask some ANT vested

@burrrata 
- +1 on vesting ANT and using 1Hive membership to use it to vote in ANV
- Also, Aragon needs examples of DAOs to actually share with the world. 1Hive does that. Let's leverage that to get support so that we can do even more cool things!

**Comment by lkngtn** [comment]
I think we should definitely pursue a grant or CFDAO proposal based on the core of the 1hive project which includes [documentation/onboarding resources](https://1hive.org/docs/contribute/welcome.html), and a portal which allows someone to deploy a "1hive" dao as a template, similar to the existing token democracy/autark templates.

However, I think we should pose this as a general "sponsorship" of the 1hive project and community, with a recurring vested ANT distribution. I think we should try and avoid specific milestones and deliverables associated and instead leave it open ended. We are value aligned already, and with the grant being vested ANT there is further value alignment. This gives us the flexibility to work on whatever we think is most valuable to us and to the wider Aragon ecosystem. 

This doesn't/shouldn't prevent us from also pursuing additional milestone/deliverable specific grants like what is being proposed in #6.

**Comment by yeqbfgxjiq** [comment]
Yeah actually that makes a lot of sense:
- a Nest Grant / CFDAO grant to support general development for 1Hive itself
- a Nest Grant specifically targeted towards the Grants Kit (#6 ) 

Would it be weird to apply for 2 Nest Grants at the same time, or is that a legit thing that projects do if they have a broad scope and large (growing) team like we do?

**Comment by 0xGabi** [comment]
Not convinced about applying on two grants. We should first probe we can deliver something like the grants kits. Then as a internal goal we should aim to further develop 1Hive on the process

**Comment by yeqbfgxjiq** [comment]
So it sounds like?
- since Nest Grants are more targeted towards deliverables and not research, Nest Grant for the MolochDAO suite
- since the CFDAO and other stuff like Gitcoin Grants is all about supporting the community and the commons, that might be a better fit for the 1Hive model specifically
- once we get the 1Hive model rolling we could potentially create a grant around a more specific goal in the future, but that's not a concern atm

**Comment by yeqbfgxjiq** [comment]
Here's my latest thinking on a 1Hive DAO Template we can ship to the world:
- rewrite the model described in the handbook (roles, responsibilities, etc...) to something generic that can be applied to any community/organization
- create a DAO Template for that generalized organization
- create a Docusaurus around it explaining what it does, why, and how to customize and extend it

This will allow Aragon DAO developers to:
- read the guides on the 1Hive Template website (note: this is **not** 1Hive.org, but a different Docusaurus website for the 1Hive Template)
- fork the repo
- deploy and configure their DAO
- update and publish the Docusaurus website in the repo, but then update it information on their DAO vs the information describing the template (kind of like how currently `docusaurus-init` launches a template that you customize)

All in one sentence: 
- A 1Hive DAO Template that allows Aragon DAO developers to deploy a 1Hive style DAO for their organization along with a Doucsaurus that provides user guides/onboarding, application docs, and a community hub for all your social channels including a built in blog.

This would accomplish a few things:
- it would make the 1Hive model accessible to the world
- it would create a standard docs template for all 1Hive apps
- it would be provide a foundation to do the same thing again when we ship the MolochDAO Suite

**Comment by yeqbfgxjiq** [comment]
Starting work on this
- https://github.com/1Hive/kit

**Comment by burrrata** [comment]
I have encountered a snafu: the Aragon CLI and/or devchain tries to open a browser with localhost to view the results of things, but my dev environment is on a headless remote VM. I don't currently know a way around this, and I can't use my local machine. Any help would be appreciated, but until then I'm going to focus on the Docs Template and the Docusaurus.

**Comment by 0xGabi** [comment]
@burrrata Not sure I understand what is the problem. How can I help you?

**Comment by burrrata** [comment]
Everything works, but then it tries to open localhost and crashes:

    Opening http://localhost:3000/#/0xB346ED613C15E2F0e4936b0435E130b3b62D008e to view your DAO
    ⚠ No front-end detected (no start_url defined)
    (node:11552) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/usr/local/lib/node_modules/@aragon/cli/node_modules/opn/index.js:85:13)
    at Object.onceWrapper (events.js:277:13)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:597:12)
    (node:11552) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch((rejection id: 2))
    (node:11552) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by burrrata** [comment]
@0xGabi moved this to https://github.com/1Hive/1hive-dao-kit/issues/3

**Comment by 0xGabi** [comment]
I recommend you delete the `/.aragon` folder so you download the wrapper again. I have experienced the same problem when the wrapper dependencies didn't installed correctly.

**Comment by burrrata** [comment]
Thanks! I'll try that :)

**Comment by burrrata** [comment]
Actually, @0xGabi let's move this conversation to https://github.com/1Hive/1hive-dao-kit/issues/3 so that this thread can stay related to grant funding for the project. Are you ok if I delete the dev-help related comments in this thread to keep it on topic?

**Comment by yeqbfgxjiq** [comment]
Not sure what happened to all the other open Issues, but if thread is where we're tracking grants ideas then I'll include the Agenda for today's meeting:
- https://hackmd.io/dsYoDv2wSVCsk1GCb-9TSA

Converted notes from the Grants Meeting to the [1Hive Nest Grant draft](https://github.com/1Hive/grants/blob/master/1hive-nest-grant.md)

**Comment by yeqbfgxjiq** [comment]
Also, as we draft the grants proposal I think it makes sense not just to talk about specifically what we're building, but also examples of potential use cases that could enable.
